export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_PENDING = "ADD_TODO_PENDING";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const DELETE_TODO_PENDING = 'DELETE_TODO_PENDING';
export const DELETE_TODO_SUCCESS =  'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const FETCH_TODOS_PENDING = "FETCH_TODOS_PENDING";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_ERROR = "FETCH_TODO_ERROR";
